In [1]:
import tensorflow as tf
import pandas as pd

# 보스턴 집값 예측

In [3]:
boston = pd.read_csv('https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv')
boston.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [23]:
independent = boston[['crim', 'zn', 'indus', 'chas', 'nox', 
            'rm', 'age', 'dis', 'rad', 'tax',
            'ptratio', 'b', 'lstat']]
dependent = boston[['medv']]
print(independent.shape, dependent.shape)

(506, 13) (506, 1)


In [24]:
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10, activation='swish')(X)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [27]:
model.fit(independent, dependent, epochs=1000, verbose=0)
model.fit(independent, dependent, epochs=100)

Epoch 1/100
16/16 [==============================] - 0s 375us/step - loss: 25.8668
Epoch 2/100
16/16 [==============================] - 0s 375us/step - loss: 24.7386
Epoch 3/100
16/16 [==============================] - 0s 375us/step - loss: 26.9548
Epoch 4/100
16/16 [==============================] - 0s 375us/step - loss: 24.3747
Epoch 5/100
16/16 [==============================] - 0s 375us/step - loss: 25.7928
Epoch 6/100
16/16 [==============================] - 0s 313us/step - loss: 25.4901
Epoch 7/100
16/16 [==============================] - 0s 375us/step - loss: 25.2204
Epoch 8/100
16/16 [==============================] - 0s 375us/step - loss: 25.4498
Epoch 9/100
16/16 [==============================] - 0s 375us/step - loss: 25.2457
Epoch 10/100
16/16 [==============================] - 0s 375us/step - loss: 24.9779
Epoch 11/100
16/16 [==============================] - 0s 375us/step - loss: 27.1975
Epoch 12/100
16/16 [==============================] - 0s 313us/step - loss: 25.0805
E

16/16 [==============================] - 0s 500us/step - loss: 24.4640
Epoch 99/100
16/16 [==============================] - 0s 500us/step - loss: 24.9027
Epoch 100/100
16/16 [==============================] - 0s 438us/step - loss: 25.9815


In [28]:
model.summary()

Model: "functional_11"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_6 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense_8 (Dense)              (None, 10)                140       
_________________________________________________________________
dense_9 (Dense)              (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [29]:
print(model.predict(independent[:5]))

[[30.879177]
 [25.586796]
 [32.014927]
 [30.825748]
 [30.378593]]


In [30]:
print(dependent[:5])

   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


# 아이리스 품종 예측

In [31]:
iris = pd.read_csv('https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv')
iris.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [32]:
iris = pd.get_dummies(iris)

In [33]:
independent = iris[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
dependent = iris[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(independent.shape, dependent.shape)

(150, 4) (150, 3)


In [34]:
x = tf.keras.layers.Input(shape=[4])
h = tf.keras.layers.Dense(8, activation='swish')(x)
h = tf.keras.layers.Dense(8, activation='swish')(h)
h = tf.keras.layers.Dense(8, activation='swish')(h)
y = tf.keras.layers.Dense(3, activation='softmax')(h)
model = tf.keras.models.Model(x, y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [35]:
model.fit(independent, dependent, epochs=100)

Epoch 1/100
5/5 [==============================] - 0s 600us/step - loss: 1.1644 - accuracy: 0.3333
Epoch 2/100
5/5 [==============================] - 0s 600us/step - loss: 1.0961 - accuracy: 0.3333
Epoch 3/100
5/5 [==============================] - 0s 600us/step - loss: 1.0591 - accuracy: 0.3533
Epoch 4/100
5/5 [==============================] - 0s 400us/step - loss: 1.0306 - accuracy: 0.5200
Epoch 5/100
5/5 [==============================] - 0s 600us/step - loss: 1.0096 - accuracy: 0.6533
Epoch 6/100
5/5 [==============================] - 0s 400us/step - loss: 0.9908 - accuracy: 0.6667
Epoch 7/100
5/5 [==============================] - 0s 600us/step - loss: 0.9745 - accuracy: 0.6667
Epoch 8/100
5/5 [==============================] - 0s 400us/step - loss: 0.9584 - accuracy: 0.6667
Epoch 9/100
5/5 [==============================] - 0s 600us/step - loss: 0.9432 - accuracy: 0.6667
Epoch 10/100
5/5 [==============================] - 0s 600us/step - loss: 0.9283 - accuracy: 0.6667
Epoch 11/

5/5 [==============================] - 0s 400us/step - loss: 0.1343 - accuracy: 0.9733
Epoch 84/100
5/5 [==============================] - 0s 600us/step - loss: 0.1325 - accuracy: 0.9733
Epoch 85/100
5/5 [==============================] - 0s 600us/step - loss: 0.1297 - accuracy: 0.9733
Epoch 86/100
5/5 [==============================] - 0s 400us/step - loss: 0.1275 - accuracy: 0.9667
Epoch 87/100
5/5 [==============================] - 0s 400us/step - loss: 0.1247 - accuracy: 0.9733
Epoch 88/100
5/5 [==============================] - 0s 400us/step - loss: 0.1215 - accuracy: 0.9733
Epoch 89/100
5/5 [==============================] - 0s 600us/step - loss: 0.1213 - accuracy: 0.9733
Epoch 90/100
5/5 [==============================] - 0s 600us/step - loss: 0.1187 - accuracy: 0.9733
Epoch 91/100
5/5 [==============================] - 0s 600us/step - loss: 0.1208 - accuracy: 0.9600
Epoch 92/100
5/5 [==============================] - 0s 400us/step - loss: 0.1139 - accuracy: 0.9667
Epoch 93/100


In [36]:
print(model.predict(independent[:5]))

[[9.9669987e-01 3.2646465e-03 3.5428784e-05]
 [9.9423450e-01 5.7056029e-03 5.9832826e-05]
 [9.9569172e-01 4.2554876e-03 5.2848969e-05]
 [9.9357831e-01 6.3479850e-03 7.3658106e-05]
 [9.9685055e-01 3.1139490e-03 3.5541558e-05]]


In [37]:
print(dependent[:5])

   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
